# Generated by Django 6.0.3 on 2026-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш файла'),
        ),
    ]
